# Change these first
owner: pacharanero # Your GitHub organization or username
repo: upptime-pacharanero # Your GitHub repository name

# Add your sites here
sites:
  - name: 2018.cawoodstock.org
    url: https://2018.cawoodstock.org
  - name: 2019.cawoodstock.org
    url: http://2019.cawoodstock.org
  - name: batsignal-live.herokuapp.com
    url: https://batsignal-live.herokuapp.com/
  - name: bawmedical.co.uk
    url: https://bawmedical.co.uk
  - name: cawood.life
    url: https://cawood.life
  - name: cawoodstock.org
    url: https://cawoodstock.org
  - name: covid19forum.rcgp.org.uk/
    url: https://covid19forum.rcgp.org.uk/
  - name: "discourse.digitalhealth.net Networks Discourse"
    url: https://discourse.digitalhealth.net/
  - name: discuss.doughnuteconomics.org
    url: https://discuss.doughnuteconomics.org
  - name: facultyofclinicalinformatics.org.uk
    url: https://facultyofclinicalinformatics.org.uk
  - name: forum.digitalhealthrewired.com
    url: https://forum.digitalhealthrewired.com
  - name: forum.ehealthireland.ie
    url: https://forum.ehealthireland.ie/
  - name: forum.greatnorthcarerecord.org.uk/
    url: https://forum.greatnorthcarerecord.org.uk
  - name: discourse.openehr.org
    url: https://discourse.openehr.org
  - name: healthforum.nz
    url: https://healthforum.nz/
  - name: www.facultyofclinicalinformatics.org.uk
    url: https://www.facultyofclinicalinformatics.org.uk
  - name: openhealthhub.org
    url: https://openhealthhub.org/
    
assignees:
  - pacharanero

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-pacharanero
  logoUrl: https://bawmedical.co.uk/uploads/default/original/1X/a94175b9df0d3e63c23d920884fdfee52bfafc72.svg
  name: Baw Medical Uptime Monitor
  introTitle: ""
  introMessage: "This site monitors important sites and catalogues Uptime, alerting upon downtime"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
